spring:
  datasource:
    url: jdbc:h2:mem:superfrogs
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create


  #setup email config
  mail:
    host: smtp.gmail.com
    port: 587
    username:
#    password will be set to env file when deploy for security
    password:
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

api:
  endpoint:
    base-url: /api/v1
