spring:
  datasource:
    url: jdbc:h2:mem:superfrogs
    username: sa
    password:
    driver-class-name: org.h2.Driver
#    url: jdbc:mysql://demo-db.cogo0zbjthrm.us-east-2.rds.amazonaws.com:3306/demo-db/?createDatabaseIfNotExist=true
#    username: admin
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

api:
  endpoint:
    base-url: /api/v1
